services:
  transport-database:
    image: postgis/postgis:16-3.4
    container_name: transport-database

    environment:
      POSTGRES_DB: ${DATASOURCE_NAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}

    ports:
      - "5435:5432"

    volumes:
      - transport-db-data:/var/lib/postgresql/data

volumes:
  transport-db-data:
